apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rickmorty-api.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "rickmorty-api.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "rickmorty-api.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rickmorty-api.fullname" . }}-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: {{ include "rickmorty-api.fullname" . }}-redis
