apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rickmorty-api.fullname" . }}-secret
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  CACHE_URL: {{ .Values.secrets.cacheUrl | quote }}
